[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
groth = "HkFStTqPEnfq4R9UiymSmqhz4gLMydQ35CvBDduHSuPw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/alan.xu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
